trigger:
- master
- maint/*

jobs:
- job: windows_amd64
  displayName: 'Windows (amd64)'
  pool:
    vmImage: 'VS2017-Win2016'
  steps:
  - checkout: self
    submodules: true
  - powershell: . '$(Build.SourcesDirectory)\build.ps1'
    displayName: 'Build'
    workingDirectory: '$(Build.BinariesDirectory)'
    env:
      CMAKE_OPTIONS: -G"Visual Studio 15 2017 Win64"
  - task: CopyFiles@2
    displayName: 'Copy Build Output'
    inputs:
      sourceFolder: $(libgit2.outputdir)
      contents: $(libgit2.libraryname)
      targetFolder: $(Build.ArtifactStagingDirectory)/win-x64/native
  - task: PublishBuildArtifacts@1
    displayName: 'Publish Library'
    inputs:
      pathToPublish: '$(Build.ArtifactStagingDirectory)'
      artifactName: 'runtimes'

- job: macos
  displayName: 'macOS'
  pool:
    vmImage: 'macOS 10.13'
  steps:
  - checkout: self
    submodules: true
  - bash: . '$(Build.SourcesDirectory)/build.sh'
    displayName: 'Build'
    workingDirectory: '$(Build.BinariesDirectory)'
  - task: CopyFiles@2
    displayName: 'Copy Build Output'
    inputs:
      sourceFolder: $(libgit2.outputdir)
      contents: $(libgit2.libraryname)
      targetFolder: $(Build.ArtifactStagingDirectory)/osx/native
  - task: PublishBuildArtifacts@1
    displayName: 'Publish Library'
    inputs:
      pathToPublish: '$(Build.ArtifactStagingDirectory)'
      artifactName: 'runtimes'

- job: package
  displayName: 'Package'
  pool:
    vmImage: 'VS2017-Win2016'
  dependsOn:
  - windows_amd64
  - macos
  steps:
  - script: choco install nuget.commandline
    displayName: 'Install Dependencies'
  - task: DownloadBuildArtifacts@0
    displayName: 'Download Build Artifacts'
    inputs:
      buildType: 'current'
      downloadPath: '$(Build.BinariesDirectory)'
      artifactName: 'runtimes'
  - powershell: . '$(Build.SourcesDirectory)\generate_props.ps1'
    displayName: 'Generate Props'
    workingDirectory: '$(Build.BinariesDirectory)'
  - powershell: nuget pack -version '0.0.$(Build.BuildId)' -basepath . $(Build.SourcesDirectory)\dogged.native.binaries.nuspec -outputdirectory '$(Build.ArtifactStagingDirectory)'
    displayName: 'Generate NuGet Package'
    workingDirectory: '$(Build.BinariesDirectory)'
  - task: PublishBuildArtifacts@1
    displayName: 'Publish NuGet Package'
    inputs:
      pathToPublish: '$(Build.ArtifactStagingDirectory)'
      artifactName: 'nuget'
